### ISSUE TITLE
OpenNeptune and display_connector not working

### ISSUE THREAD

**Issue by dsrdakota** [OpenNeptune3D/display_connector#25]
So far I have the latest version of everything installed.
OpenNeptune - latest
display_connector - latest (had modified a few files to get pillow working, ie. some python wheels and modules had to be updated)
display_firmware - latest (tried running display_connector service with stock/oem screen firmware and ON custom firmware)

I am running the latest versions of klipper, moonraker and fluidd. I have the Neptune 4 Pro.
Here is a sample log with custom firmware.

`2024-11-04 01:00:09,568 - INFO - Loading config
2024-11-04 01:00:10,650 - INFO - Connecting to Moonraker at /home/mks/printer_data/comms/moonraker.sock
2024-11-04 01:00:10,652 - INFO - Connected to Moonraker
2024-11-04 01:00:10,660 - INFO - Software Version: v0.12.0-317
2024-11-04 01:00:10,670 - DEBUG - Client Identified With Moonraker: 281473499544600
2024-11-04 01:00:10,730 - INFO - Display Type: OpenNeptune4DisplayCommunicator
2024-11-04 01:00:10,731 - INFO - Printer Model: Neptune 4 Pro
2024-11-04 01:00:10,751 - INFO - Status Update: standby
2024-11-04 01:00:10,957 - DEBUG - Navigating to main
2024-11-04 01:00:11,001 - INFO - Machine Size: 235x235x268

Exception in callback SerialTransport._read_ready()
handle: <Handle SerialTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mks/display_connector/venv/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 120, in _read_ready
    self._protocol.data_received(data)
  File "/home/mks/display_connector/src/tjc.py", line 56, in data_received
    message, was_keyboard_input = self._extract_packet()
  File "/home/mks/display_connector/src/tjc.py", line 74, in _extract_packet
    return self._extract_fixed_length_packet(expected_length)
  File "/home/mks/display_connector/src/tjc.py", line 105, in _extract_fixed_length_packet
    self.dropped_buffer += message + self.EOL
TypeError: can only concatenate tuple (not "bytes") to tuple
2024-11-04 01:06:45,681 - ERROR - Failed to write to display: Variable name invalid for command: adjusttemp_pro.out_bedtemp.txt="21.8°C"
Task exception was never retrieved
future: <Task finished coro=<DisplayCommunicator.update_data() done, defined at /home/mks/display_connector/src/communicator.py:86> exception=CommandFailed('Variable name invalid for command: adjusttemp_pro.out_bedtemp.txt="21.8°C"')>
Traceback (most recent call last):
  File "/home/mks/display_connector/src/communicator.py", line 94, in update_data
    await self._update_data_recursive(new_data, data_mapping, current_data)
  File "/home/mks/display_connector/src/communicator.py", line 106, in _update_data_recursive
    await self._update_data_recursive(value, mapping_value, mapping_current)
  File "/home/mks/display_connector/src/communicator.py", line 108, in _update_data_recursive
    await self._update_data_leaf(value, mapping_value)
  File "/home/mks/display_connector/src/communicator.py", line 119, in _update_data_leaf
    await self.write(command)
  File "/home/mks/display_connector/src/communicator.py", line 52, in write
    await self.display.command(data, timeout if timeout is not None else self.timeout)
  File "/home/mks/display_connector/venv/lib/python3.7/site-packages/nextion/client.py", line 331, in command
    return await self._command(command, timeout=timeout, attempts=attempts)
  File "/home/mks/display_connector/venv/lib/python3.7/site-packages/nextion/client.py", line 294, in _command
    raise CommandFailed(command, response_code)
nextion.exceptions.CommandFailed: Variable name invalid for command: adjusttemp_pro.out_bedtemp.txt="21.8°C"
Exception in callback SerialTransport._read_ready()
handle: <Handle SerialTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mks/display_connector/venv/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 120, in _read_ready
    self._protocol.data_received(data)
  File "/home/mks/display_connector/src/tjc.py", line 56, in data_received
    message, was_keyboard_input = self._extract_packet()
  File "/home/mks/display_connector/src/tjc.py", line 74, in _extract_packet
    return self._extract_fixed_length_packet(expected_length)
  File "/home/mks/display_connector/src/tjc.py", line 105, in _extract_fixed_length_packet
    self.dropped_buffer += message + self.EOL
TypeError: can only concatenate tuple (not "bytes") to tuple
Exception in callback SerialTransport._read_ready()
handle: <Handle SerialTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mks/display_connector/venv/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 120, in _read_ready
    self._protocol.data_received(data)
  File "/home/mks/display_connector/src/tjc.py", line 56, in data_received
    message, was_keyboard_input = self._extract_packet()
  File "/home/mks/display_connector/src/tjc.py", line 74, in _extract_packet
    return self._extract_fixed_length_packet(expected_length)
  File "/home/mks/display_connector/src/tjc.py", line 105, in _extract_fixed_length_packet
    self.dropped_buffer += message + self.EOL
TypeError: can only concatenate tuple (not "bytes") to tuple
^CTraceback (most recent call last):
  File "/home/mks/display_connector/display.py", line 1441, in <module>
    loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)`

**Comment by Damon20r** [comment]
I updated several......modules? and am now also having issues with my display not working.  It shows a continuous loading Elegoo logo.  I am NOT by any stretch of anybody's imagination a dev or programmer.  I am getting moonraker warnings of an invalid path along with three unparsed warnings that I assume are related to the file it can't find. 

![image](https://github.com/user-attachments/assets/3552ba6e-12ed-4ba3-bddf-0aef27961b92)

Not sure where else to go to look for advice.  Thanks in advance.

**Comment by jimmycr** [comment]
Had the same problem after klipper / moonraker update today. This resolved my problem:
- SSH into the printer
- go to directory: /home/mks/display_connector
- run script: ./display-service-installer.sh
- enjoy ;-)

**Comment by Damon20r** [comment]
Thank you! I'll give that a try.

**Comment by Damon20r** [comment]
It worked like a charm. Thanks a million! I just need to stop updating it because every time I do it seems like something screws up. That's the reason why I am now using a P1S.

**Comment by petermcgarvey1111** [comment]
When I tried the solution above I got the following error about halfway through install, any idea why?

ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    numpy from https://files.pythonhosted.org/packages/27/2f/21b94664f23af2bb52030653697c685022119e0dc93d6097c3cb45bce5f9/numpy-2.1.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (from -r /home/mks/display_connector/requirements.txt (line 7)):
        Expected sha256 762479be47a4863e261a840e8e01608d124ee1361e48b96916f38b119cfda04a
             Got        b3caa77e071cd5d269f1de8e6b07539af006ad61d5b756a6035b3aa970d2c669

**Comment by Entasdisk1** [comment]
It seems like I don't have a directory. When I do 5) Install/Update Touch-Screen Service (BETA) from OpenNept4une, the folder is not created.

![Ekran görüntüsü 2024-12-25 134623](https://github.com/user-attachments/assets/d665d74e-51c6-4082-af8f-d72ef459a292)

**Comment by MisterEvi1** [comment]
> Had the same problem after klipper / moonraker update today. This resolved my problem:
> 
>     * SSH into the printer
> 
>     * go to directory: /home/mks/display_connector
> 
>     * run script: ./display-service-installer.sh
> 
>     * enjoy ;-)

Doesn't work for me :((
![photo_2024-12-27_15-14-00](https://github.com/user-attachments/assets/959523ee-f5ac-4614-a87a-945d58f9e953)
![photo_2024-12-27_15-13-59](https://github.com/user-attachments/assets/86056ccd-4507-4e55-ba4b-d4603a9f5c4b)
![photo_2024-12-27_15-13-58](https://github.com/user-attachments/assets/eb41fa2c-a706-4861-a608-f38860dbe979)
![photo_2024-12-27_15-13-56](https://github.com/user-attachments/assets/5831bf16-70cd-4cbf-9859-2d9d9b2389c4)

**Comment by zingo** [comment]
@Entasdisk1 @MisterEvi1 

> It seems like I don't have a directory. When I do 5) Install/Update Touch-Screen Service (BETA) from OpenNept4une, the folder is not created.

I don't think you have the same problem but a new one that started from the dev->main merge 3 days ago, I sugest you open a new separate tickat as your problem might probably be missed if not.

**Comment by Entasdisk1** [comment]
> Hi @Entasdisk1 @MisterEvi1
> 
> > It seems like I don't have a directory. When I do 5) Install/Update Touch-Screen Service (BETA) from OpenNept4une, the folder is not created.
> 
> I don't think you have the same problem but a new one that started from the dev->main merge 3 days ago, I sugest you open a new separate tickat as your problem might probably be missed if not.
> 
> See [OpenNeptune3D/OpenNept4une#234](https://github.com/OpenNeptune3D/OpenNept4une/pull/234)
> 
> If it was me I would recoment creating the issue/ticket on the other/main git e.g. https://github.com/OpenNeptune3D/OpenNept4une/issues


I did the latest updates. The screen in this article has yellow text.
In the commands given for the solution, it says there is no such folder.
The screen was working before the update.
After doing display_firmware, it broke.
I can use the printer without the screen.

**Comment by zingo** [comment]
Reading the last comments from the last 2 days, I guess there might be a new problem caused by something in the update flow, so I think it would be good to create a new separate ticket in the other git so the devs can see it more easily.
I would think/expect looking at this older ticket might be lower prio for the devs. I have not done the update yet and will probably wait to see if your issues are sorted out so I can't help much, sorry

**Comment by zingo** [comment]
I tested this on my printer and get something like this, in my case the folder /home/mks/display_connector was missing. 
I think I got into this state when the web gui asked if it should reapis something with the display_connector and I let it do it.

I think manage to fix it by running this on my printer by hand

```
cd /home/mks/
git clone https://github.com/OpenNeptune3D/display_connector.git
/home/mks/display_connector/display-service-installer.sh
```
I alos spot that on the dev branch this just got merged 
https://github.com/OpenNeptune3D/OpenNept4une/commit/c6f6c316e0c1e8b8223e18a7146c1c756f074682
Maybe this will also fix the problem when merged to main ?

**Comment by JoeDante** [comment]
> I manage to fix my problem by running this on my printer by hand to bring back the folder:
> 
> ```
> cd /home/mks/
> git clone https://github.com/OpenNeptune3D/display_connector.git
> /home/mks/display_connector/display-service-installer.sh
> ```

My display stopped working, this solved my problem! 
THANK YOU SO MUCH!
