### ISSUE TITLE
Support Neptune 3 Series?

### ISSUE THREAD

**Issue by ramdaron** [OpenNeptune3D/display_connector#8]
Hello.

From the project description, it is optimized for Neptune 4 Series. Are there any plans to add support for the Neptune 3 Series?

As far as I understand, the key differences are that klipper runs on a separate board and a slight difference in hardware (in particular, the lack of backlighting on the print head).

I've seen a couple of projects that implement screen support for klipper on Neptune 3, but your project looks much better.

**Comment by phillipthelen** [comment]
Yes, there are plans. I'm currently working on abststracting more of the code and making some more things adjustable. One member already managed to run the project on his Neptune 3 with Klipper.
Instructions for how to connect the display to the raspberry pi running Klipper are here: https://github.com/joakimtoe/KlipperLCD/tree/main

**Comment by ramdaron** [comment]
> One member already managed to run the project on his Neptune 3 with Klipper.

I also managed to run the project by connecting the display via a usb2tll adapter, and I encountered the same problems and solved them in the same way.

I installed the project manually on ubuntu 20.04 and successfully ran it with python 3.8.10, using old intel atom (no wifi) as host. In this case, the system does not have the `nmcli` utility, and upon startup an error occurs:

> Task exception was never retrieved
> future: <Task finished name='Task-17' coro=<DisplayController.special_page_handling() done, defined at /home/klipper/display_connector-main/display.py:256> exception=FileNotFoundError(2, 'No such file or directory')>
> Traceback (most recent call last):
>   File "/home/klipper/display_connector-main/display.py", line 259, in special_page_handling
>     has_wifi = self.update_wifi_ui()
>   File "/home/klipper/display_connector-main/display.py", line 617, in update_wifi_ui
>     has_wifi, ssid, rssi_category = get_wlan0_status()
>   File "/home/klipper/display_connector-main/src/wifi.py", line 6, in get_wlan0_status
>     ssid_output = subprocess.check_output(['nmcli', '-t', '-f', 'active,ssid', 'dev', 'wifi']).decode('utf-8')  # nosec B603, B607
>   File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.8/subprocess.py", line 493, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'nmcli'

I solved this problem by adding an exception handler to the `get_wlan0_status` function in the `wifi.py` file:
`    except FileNotFoundError:`
`        return False, None, None`

> Yes, there are plans. I'm currently working on abststracting more of the code and making some more things adjustable.

This is great news, I will monitor the project updates. Thank you!
